apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sm-object-storage
  namespace: sm-platform
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sm-object-storage.sm-platform.example.com
      secretName: sm-object-storage-tls
  rules:
    - host: sm-object-storage.sm-platform.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sm-object-storage
                port:
                  number: 8300
