"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:08:52.728559
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifecycle_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bucket_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expiration_days', sa.Integer(), nullable=False),
    sa.Column('transitions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_id', 'prefix', name='uq_rule_bucket_prefix')
    )
    op.create_index(op.f('ix_lifecycle_rules_bucket_id'), 'lifecycle_rules', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_lifecycle_rules_status'), 'lifecycle_rules', ['status'], unique=False)
    op.create_table('storage_buckets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('storage_class', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('versioning_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_buckets_name'), 'storage_buckets', ['name'], unique=True)
    op.create_index(op.f('ix_storage_buckets_status'), 'storage_buckets', ['status'], unique=False)
    op.create_table('storage_objects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bucket_id', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('etag', sa.String(length=64), nullable=False),
    sa.Column('storage_class', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_id', 'object_key', name='uq_object_bucket_key')
    )
    op.create_index(op.f('ix_storage_objects_bucket_id'), 'storage_objects', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_storage_objects_object_key'), 'storage_objects', ['object_key'], unique=False)
    op.create_index(op.f('ix_storage_objects_status'), 'storage_objects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_objects_status'), table_name='storage_objects')
    op.drop_index(op.f('ix_storage_objects_object_key'), table_name='storage_objects')
    op.drop_index(op.f('ix_storage_objects_bucket_id'), table_name='storage_objects')
    op.drop_table('storage_objects')
    op.drop_index(op.f('ix_storage_buckets_status'), table_name='storage_buckets')
    op.drop_index(op.f('ix_storage_buckets_name'), table_name='storage_buckets')
    op.drop_table('storage_buckets')
    op.drop_index(op.f('ix_lifecycle_rules_status'), table_name='lifecycle_rules')
    op.drop_index(op.f('ix_lifecycle_rules_bucket_id'), table_name='lifecycle_rules')
    op.drop_table('lifecycle_rules')
    # ### end Alembic commands ###
